version : '3'

services:

    pgsql:
        image: postgres
        container_name: dash_pgsql
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=XXX
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    dash:
        build:
            context: /app
            dockerfile: Dockerfile.dash
        container_name: dash_app
        command: python app.py 
        volumes:
            - .:/app 
        ports:
            - "80:8050"
        depends_on:
            - pgsql
